networks:
  proxy:
    external: true

volumes:
  evcc_data: {}

services:
  evcc:
    command:
      - evcc
    container_name: evcc
    networks: 
      - proxy
    image: evcc/evcc:0.300.8@sha256:ddf2a25afce51eccdd3ede83f174a87acd3ed3aadbd3db177466ff7a365dfa65
    ports:
      - 8887:8887/tcp
      - 9522:9522/udp
      - 4712:4712/tcp
    volumes:
      #- /mnt/evcc/evcc.yaml:/etc/evcc.yaml
      - evcc_data:/root/.evcc
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
    labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.evcc.entryPoints=websecure"
        - "traefik.http.routers.evcc.tls.certResolver=production"
        - "traefik.http.routers.evcc.rule=Host(`evcc.$DOMAIN`)"
        - "traefik.http.services.evcc.loadbalancer.server.port=443"
        - "traefik.http.routers.evcc.tls.domains[0].main=$DOMAIN"
        - "traefik.http.routers.evcc.tls.domains[0].sans=*.$DOMAIN"
        - "traefik.http.routers.evcc.tls=true"
    restart: unless-stopped