networks:
  proxy:
    external: true

volumes:
  esphome_data: {}

services:
  esphome:
    container_name: esphome
    image: esphome/esphome:2026.1.5@sha256:75adfbe90d9afe52c5137decf8cf12369cee00b1acfe2a92e866bfe0d1887904
    networks: 
      - proxy
    volumes:
      - esphome_data:/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.esphome.entryPoints=websecure"
      - "traefik.http.routers.esphome.tls.certResolver=production"
      - "traefik.http.routers.esphome.rule=Host(`esphome.$DOMAIN`)"
      - "traefik.http.routers.esphome.tls.domains[0].main=$DOMAIN"
      - "traefik.http.routers.esphome.tls.domains[0].sans=*.$DOMAIN"
      - "traefik.http.routers.esphome.tls=true"
    restart: unless-stopped