networks:
  proxy:
    external: true

volumes:
  esphome_data: {}

services:
  esphome:
    container_name: esphome
    image: esphome/esphome:2025.11.3@sha256:c9db5a84e817185b5ff6c1fbf240565f453e754b1cd29feca8e75eeeb485f078
    networks: 
      - proxy
    volumes:
      - esphome_data:/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.esphome.entryPoints=websecure"
      - "traefik.http.routers.esphome.tls.certResolver=production"
      - "traefik.http.routers.esphome.rule=Host(`esphome.$DOMAIN`)"
      - "traefik.http.routers.esphome.tls.domains[0].main=$DOMAIN"
      - "traefik.http.routers.esphome.tls.domains[0].sans=*.$DOMAIN"
      - "traefik.http.routers.esphome.tls=true"
    restart: unless-stopped