networks:
  proxy:
    external: true

volumes:
  esphome_data: {}

services:
  esphome:
    container_name: esphome
    image: esphome/esphome:2025.12.7@sha256:cccd0a0b3de9ea0fc167a5a3666dbcc20150aa240f5ab412d57f87ac6c605bef
    networks: 
      - proxy
    volumes:
      - esphome_data:/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.esphome.entryPoints=websecure"
      - "traefik.http.routers.esphome.tls.certResolver=production"
      - "traefik.http.routers.esphome.rule=Host(`esphome.$DOMAIN`)"
      - "traefik.http.routers.esphome.tls.domains[0].main=$DOMAIN"
      - "traefik.http.routers.esphome.tls.domains[0].sans=*.$DOMAIN"
      - "traefik.http.routers.esphome.tls=true"
    restart: unless-stopped