networks:
  proxy:
    external: true

volumes:
  esphome_data: {}

services:
  esphome:
    container_name: esphome
    image: esphome/esphome:2026.1.0@sha256:4d099caf254a03aa7fbb8ced3ca65aa7777891181fa3236fc2821cf8f9be5b6b
    networks: 
      - proxy
    volumes:
      - esphome_data:/config
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.esphome.entryPoints=websecure"
      - "traefik.http.routers.esphome.tls.certResolver=production"
      - "traefik.http.routers.esphome.rule=Host(`esphome.$DOMAIN`)"
      - "traefik.http.routers.esphome.tls.domains[0].main=$DOMAIN"
      - "traefik.http.routers.esphome.tls.domains[0].sans=*.$DOMAIN"
      - "traefik.http.routers.esphome.tls=true"
    restart: unless-stopped