---
volumes:
  wmbusmeters:

services:
  wmbusmeters:
    image: wmbusmeters/wmbusmeters:latest@sha256:0f6325a6f2d8960a6b111e36b20620e07a391b37aa2f1575d281c809d82b9977
    container_name: wmbusmeters
    privileged: true
    restart: always
    volumes:
      - wmbusmeters:/wmbusmeters_data
      - /etc/localtime:/etc/localtime:ro
      - /dev/:/dev/
    environment:
      - TZ=Europe/Berlin
      - MQTT_PORT=$MQTT_PORT
      - MQTT_PASSWORD=$MQTT_PASSWORD
      - MQTT_USER=$MQTT_USER
      - MQTT_HOST=$MQTT_HOST
