---
volumes:
  wmbusmeters:

services:
  wmbusmeters:
    image: wmbusmeters/wmbusmeters:latest@sha256:6fa3720772d2c42a62e5e6be5c05f51fdfd75c510e10761c4104f4a26ca6f978
    container_name: wmbusmeters
    privileged: true
    restart: always
    volumes:
      - wmbusmeters:/wmbusmeters_data
      - /etc/localtime:/etc/localtime:ro
      - /dev/:/dev/
    environment:
      - TZ=Europe/Berlin
      - MQTT_PORT=$MQTT_PORT
      - MQTT_PASSWORD=$MQTT_PASSWORD
      - MQTT_USER=$MQTT_USER
      - MQTT_HOST=$MQTT_HOST
