---
volumes:
  wmbusmeters:

services:
  wmbusmeters:
    image: wmbusmeters/wmbusmeters:latest@sha256:4392b55c20f826524b42340ddd97faddd43f23e6cddcbb61ec79d6fa79fd8fe8
    container_name: wmbusmeters
    privileged: true
    restart: always
    volumes:
      - wmbusmeters:/wmbusmeters_data
      - /etc/localtime:/etc/localtime:ro
      - /dev/:/dev/
    environment:
      - TZ=Europe/Berlin
      - MQTT_PORT=$MQTT_PORT
      - MQTT_PASSWORD=$MQTT_PASSWORD
      - MQTT_USER=$MQTT_USER
      - MQTT_HOST=$MQTT_HOST
