---
# yamllint disable rule:line-length
volumes:
  data:

networks:
  proxy:
    external: true

services:
  uptime-kuma:
    container_name: uptime-kuma
    # Once V2 is out switch to ghcr.io
    image: ghcr.io/louislam/uptime-kuma:2.1.0@sha256:da418b1f5655c12d2d62aa3d189117bfad5d83c2ab99bb3e82b2eaaf5246bbc1
    environment:
      - TZ=Europe/Berlin
    volumes:
      - data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: "true"
      traefik.http.routers.uptime-kuma.entrypoints: "websecure"
      traefik.http.routers.uptime-kuma.rule: "Host(`uptimekuma.$DOMAIN`)"
      traefik.http.routers.uptime-kuma.tls: "true"
      traefik.http.routers.uptime-kuma.tls.certresolver: "production"
      traefik.http.routers.uptime-kuma.tls.domains[0].main: "$DOMAIN"
      traefik.http.routers.uptime-kuma.tls.domains[0].sans: "*.$DOMAIN"
      traefik.docker.network: "proxy"
