---
volumes:
  wmbusmeters:

services:
  wmbusmeters:
    image: wmbusmeters/wmbusmeters:latest@sha256:f72ace2f7d0b125e681dfadcff282abaf7f3287d35d0e2b6126167872c3397a9
    container_name: wmbusmeters
    privileged: true
    restart: always
    volumes:
      - wmbusmeters:/wmbusmeters_data
      - /etc/localtime:/etc/localtime:ro
      - /dev/:/dev/
    environment:
      - TZ=Europe/Berlin
      - MQTT_PORT=$MQTT_PORT
      - MQTT_PASSWORD=$MQTT_PASSWORD
      - MQTT_USER=$MQTT_USER
      - MQTT_HOST=$MQTT_HOST
