---
# yamllint disable rule:line-length

networks:
  proxy:
    external: true
  immich:

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v2.5.5@sha256:161b1ec8af9e0478797cfd75ea857c7e55af271fa7cea103cb30ab1ba5b418d8
    volumes:
      - immich_upload:/usr/src/app/upload/upload
      - immich_thumbs:/usr/src/app/upload/thumbs
      - immich_encoded_video:/usr/src/app/upload/encoded-video
      - immich_profile:/usr/src/app/upload/profile
      - immich_library:/usr/src/app/upload/library
      - immich_backups:/usr/src/app/upload/backups
      - /etc/localtime:/etc/localtime:ro
    networks:
      - immich
      - proxy
    depends_on:
      - redis
      - database
    env_file:
      - stack.env
    restart: always
    labels:
      traefik.enable: "true"
      traefik.http.routers.immich.entrypoints: "websecure"
      traefik.http.routers.immich.rule: "Host(`$HOST`) || Host(`$EXTERNAL_HOST`)"
      traefik.http.routers.immich.tls: "true"
      traefik.http.routers.immich.tls.certresolver: "production"
      traefik.http.routers.immich.tls.domains[0].main: "$DOMAIN"
      traefik.http.routers.immich.tls.domains[0].sans: "*.$DOMAIN"
      traefik.docker.network: "proxy"
      homepage.name: immich
      homepage.group: Services
      homepage.icon: immich
      homepage.href: https://$HOST
      homepage.description: immich
      homepage.widget.type: immich
      homepage.widget.version: 2
      homepage.widget.url: https://$HOST
      homepage.widget.key: $HOMEPAGE_KEY
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v2.5.5@sha256:2e17e15855907ece0d5b3a7bf625b12f6d987a5854fa71d888641acae28b0323
    volumes:
      - model-cache:/cache
    networks:
      - immich
    restart: always
    env_file:
      - stack.env
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571
    networks:
      - immich
    restart: always
    healthcheck:
      test: redis-cli ping || exit 1

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:18-vectorchord0.5.3@sha256:c5212b5b9250bc397c978217ddee323f4010f1e02714045a4a28e33ea92af3ff
    networks:
      - immich
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - pgdata:/var/lib/postgresql
    restart: always

volumes:
  pgdata:
  model-cache:
  immich_upload:
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=192.168.1.14,rw"
      device: ":/mnt/pool-main/docker_volumes/immich/upload"
  immich_backups:
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=192.168.1.14,rw"
      device: ":/mnt/pool-main/docker_volumes/immich/backups"
  immich_profile:
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=192.168.1.14,rw"
      device: ":/mnt/pool-main/docker_volumes/immich/profile"
  immich_library:
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=192.168.1.14,rw"
      device: ":/mnt/pool-main/docker_volumes/immich/library"
  immich_thumbs:
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=192.168.1.14,rw"
      device: ":/mnt/pool-main/no_backup/immich_thumbs"
  immich_encoded_video:
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=192.168.1.14,rw"
      device: ":/mnt/pool-main/no_backup/immich_encoded_video"
