---
networks:
  proxy:
    external: true

volumes:
  traefik:

services:
  traefik:
    container_name: "traefik"
    environment:
      CF_DNS_API_TOKEN: $CF_DNS_API_TOKEN
    image: traefik:v3.6.9@sha256:9004e1cd1e33c5eb0b6ec02bc6cfda61fe9caca36751114b1c9c6662f01b264a
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true
    ports:
      - "443:443/tcp"
      - "80:80/tcp"
    restart: "unless-stopped"
    volumes:
      - "traefik:/etc/traefik"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/localtime:/etc/localtime:ro"
    healthcheck:
      test: ['CMD', 'traefik', 'healthcheck', '--ping']
      interval: 10s
      timeout: 10s
      retries: 5
    labels:
      traefik.enable: true
      traefik.http.routers.traefik_https.rule: Host(`traefik.$DOMAIN`)
      traefik.http.routers.traefik_https.entrypoints: websecure
      traefik.http.routers.traefik_https.tls: true
      traefik.http.routers.traefik_https.tls.certResolver: production
      traefik.http.routers.traefik_https.tls.domains[0].main: "$DOMAIN"
      traefik.http.routers.traefik_https.tls.domains[0].sans: "*.$DOMAIN"
      traefik.http.routers.traefik_https.service: api@internal
      traefik.http.routers.traefik_https.middlewares: basic-auth-global
      traefik.http.middlewares.basic-auth-global.basicauth.users: $BASIC_AUTH
      traefik.http.routers.http-catchall.rule: hostregexp(`{host:.+}`)
      traefik.http.routers.http-catchall.entrypoints: web
      traefik.http.routers.http-catchall.middlewares: redirect-to-https
      traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
      homepage.name: Traefik
      homepage.group: Services
      homepage.icon: traefik
      homepage.href: https://traefik.$DOMAIN
      homepage.description: Traefikmanagement
      homepage.widget.type: traefik
      homepage.widget.url: https://traefik.$DOMAIN
      homepage.widget.username: $HOMEPAGE_USER
      homepage.widget.password: $HOMEPAGE_PASSWORD